### ISSUE TITLE
DNS linking not working

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/stdlib-source#179]
When doing the following query:

https://app.overmind.tech/explore?type=http&method=GET&linkDepth=4&query=https%3A%2F%2Fwww.reddit.com

I get the following graph:

<img width="1101" alt="Screenshot 2024-01-09 at 2 16 03 pm" src="https://github.com/overmindtech/stdlib-source/assets/8799341/6be80b2c-d11e-4ebe-b84b-13453aeab1c4">

I would have expected the `www.reddit.com` DNS entry to be related to the `dualstack.reddit.map.fastly.net.` entry since one is a CNAME of the other

**Comment by dylanratcliffe** [comment]
Also when I reload the same query I get this:

<img width="1042" alt="Screenshot 2024-01-09 at 2 20 45 pm" src="https://github.com/overmindtech/stdlib-source/assets/8799341/048b5033-8114-42a4-ad5f-0f20f9b6c641">

Note that the DNS is now directly linked to IPs. I think this is because it's running a GET request which DNS does respond to. Potentially it shouldn't? Or maybe it should respond the same way SEARCH does? Probably the lartter...

**Comment by DavidS-ovm** [comment]
👀 https://github.com/overmindtech/stdlib-source/blob/1d57698c39f5ac6e9db8880660f09906945fe4e7/sources/network/dns.go#L143-L146

**Comment by DavidS-ovm** [comment]
just reran the OG query and got what I would say is the correct result.

overmind account:
![Image](https://github.com/overmindtech/stdlib-source/assets/118179693/44cc1433-7740-468d-8d40-109c6b9bb82c)

playground:
![Image](https://github.com/overmindtech/stdlib-source/assets/118179693/50024c0a-b1c9-41b0-bbb5-96e22bc90db7)


Note that apparently reddit has changed its dns structure (dualstack -> map) since the report, or dylan and I are seeing different results from DNS (I have native ipv6 connectivity).
